apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare
    namespace: kube-system
type: Opaque
data:
    apiKey: ENC[AES256_GCM,data:sfJqtfEmJrg9Qfa3vUIQNlEjhoSchl0iKAmukgymD4m59apKffkxEEOCZ/YiUQnli6mRGpg=,iv:MrE/u3kSZFv+OeQk2GS8lmzc4h3XBLQqqR23ztdYnUE=,tag:7T9uLo5Y+zOyk2SIYIoskw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T07:00:00Z"
    mac: ENC[AES256_GCM,data:NHiVEQSSsgKPf0Nbct6Lr2ogvDBOJxtHTD7kxHvktLBCCfISue+RLuO9Q7yRP0pDHTpAFYlg0wIUWNCC3gdP1KxjwjoCoj/DjfzfnVIVqDW0nt2d+Xy8Ce4Mlgj6XJwvyO0vDPhltx7+eEVLKy+sh8OyEJ6g6QKWTldjBbut3+c=,iv:P6g8Hhg/XUDRL+HonJBr/bJWko2Z2D3Mqc36lZ0mBcI=,tag:3+12c0J2pm7zEhW0xiBv0g==,type:str]
    pgp:
        - created_at: "2026-05-24T07:00:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/J2BiN+msR8AQ//VFJ8rTFBOU/7J0kAQQcx3k2WXfJWbwAT2NVwmLSdsYFY
            30MSYGV2YPCWytVr0lwxY3Iyaj85eiLOZ6t6NEPB2pwWPeZnyLClrm7Hw+NKRRWf
            dBwiibI1/0oacUN0EP9g8Xx70cQbCo561Kz2Ok0H9aQ1w/69h7Isv/gk97HOxeKt
            ihERdFT0IDQfcPTl3ylxPVgmV/I+2KXdBzqe+4FqXK0KC/xpZ5D6PG0yqFMjnK9O
            /VYvdBoRqlWkshCgLKfcOIJbcFxvDNgqPgoPzI5gqdvjLbb7zHHVcc/f5ezPSGdx
            YcItp3F2De/cPe0nl8hYuXi26BHoRLT1UkoKqzIRB+KM/sIiBt0X6U9BShKXd304
            YC93h0Wu2iPH9zYZPN+Wbxdg5e0ADK4IqGWn64lvquioPfR0vsubgeNeodO6PxK5
            bukhyAOFjJChoouHS/5Pw6kcDwIWQ0KxketrliiHq9Z3vpLOxsLUWdaCk1IPh7QB
            pIit0XY6Q2lVU7JcpdcKcLAlrpSA5xaar4OdelUR94opiO1Q2LPEYi6mlp/ZsenC
            LuT3oNsgx2LzkDZlEpbYBN+remvsZ3xoXfzUvvmE5fcTHQAxUa23kvaR6n50uUyQ
            MSL2zvtUIb+P/hTPl3dIqVb4FoA+RnnsReyzvyEdGHkcowZ0Q2ARXVdx9EJHc2/S
            XgFP84cH5ozE759jkd8jWVEWBzBKdeB+no68w9kaAatfVQD1vib+CJYKqKTCLggW
            8e6RzVCwQ96d9Q3G1VfCSiHfxeVD0jMXQB3M58kuBhpNCRuNHEcFDHd6ytE3AiQ=
            =RHuT
            -----END PGP MESSAGE-----
          fp: 04B1FD9EEE0A46AD62CCFF8C2EE05AF20EB391BA
    version: 3.13.0
