apiVersion: v1
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: monitoring
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: alertmanager-slack-api-secret
    namespace: monitoring
type: Opaque
data:
    url: ENC[AES256_GCM,data:CwGxTIYmwdsiJkdVrUsg+nAY64z0TWSCDVdGAr0qfAw6l8L1DU+MFpDdp/41S9SfZIs8zHnMCPlcJOowyGatSiK9EHLzdk3OT7RwQdXUPQ==,iv:QvdXv4ta5r+BTS8gKs1nDfllJK20fSQeT2kdQgo0k+k=,tag:XPVRWXNjNeLgZ36OzvCp9g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T06:44:23Z"
    mac: ENC[AES256_GCM,data:i4hRVPmWPL5NPpsLFqwqvOkKZXntKo5OBo1HfIZZJbShHKy0EMtoBkek96A8rRiaZzF4EIbDdAgT5nxBLTsKJUrxMzrkqN+g6i2EleZ7Dn27Vwoo4M9Yur3FeCS3bGIslTRhPEsrgaAHf8tE9qDolW25BmmTet8/90MdhOEhiFI=,iv:hE3/l5cHYqSwxeB5f7DFN75wP9giFMNAeNkKDdNAGoo=,tag:x1zQ+yPwYvdkxnc3XE2DAA==,type:str]
    pgp:
        - created_at: "2026-05-24T06:44:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/J2BiN+msR8AQ/9FlCH5h7kPkBC2YG3mUY0uZ06GQXeSNq+tTmNDuoVd2Y6
            /3iZrPxA/JMNd8SX04LgaWBChPNru0txvhpzN8t4AgugWtVdDjhfCK5UWW/4GP1X
            yhUNfSJfCsYd9/gqDbGEMmG3J/5yV9z0UZoCWZBuoBqoDMceLI82/RGvK5/nLSpo
            rUohfHPdcWufTsX1MEMzW/SuToWE2jyh+z7v7dnP4zOEadvxhiWl0zCQcTkChumj
            ekpmOAvJR4Q3+uMzZzSqcI0GEqd7voT/JJh/AIdpYir6qY9oF19lvgeKqzmT6zk0
            jgR2qh5kQgTTCNdGXX3tfS7eMTQwkjZmMHY3Ru09GywaB+YFbpBFv/3v0ZFClDWs
            Dd2dS49i8ZCSA7wM9MkDZwno8WZ9f3kos1I8P88Rn13sMRl10iAVIOYIBidQsX4s
            6T6QYFP/qHesnGhcW/KS5wlbd4RRDRgfxhYueYBdE6bQXl7Ny2oMBL1U6rerBt1T
            UVJevj6/4CUXD0mdOa+9IKYSyVZES+jv1Jsdv4vXYENPDvkPWIOCuT1g38WRjEFi
            rP9caeBV1+6Y8r94mIH9skJhxEWhJUiyHVYbVV2hs7Oz8XC1GYQFl8KLxWWWEiAZ
            AZa9HcgiTHn580u5AT9yu/Ntho8L0TOEH0ksP2ahs+IuO7s4LH613E2nTglInTvS
            XgFiDpQGeA7qlhp/E2fEbxckc9eHn5jdR2awRlNsBq+ykQZgBifd+eBtvnJsZsg/
            wOe9U/gf4ClHl/zTfXtPj5HfikI8TrfvR5qQKFjlNi0Agb7xyEln1jw9gBwNvH0=
            =O7QX
            -----END PGP MESSAGE-----
          fp: 04B1FD9EEE0A46AD62CCFF8C2EE05AF20EB391BA
    version: 3.13.0
