apiVersion: v1
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: monitoring
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: prom-stack-grafana-pass
    namespace: monitoring
type: Opaque
data:
    values.yaml: ENC[AES256_GCM,data:hfXDq/rZd7OZi8fNeEcqpfan7+6U4GSDE0mJJlBmfMXvh213oboUgLO6aVMR1Ijh,iv:+Zndwcs4eorcc6QjmQc4FK7UdZyGDYzXTeNo2FckVD8=,tag:Ptn7gB5G4EMIZdALa3uWCA==,type:str]
# encode with base64 a string like below
# grafana:
#   adminPassword: [YOUR_PASS]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T06:33:22Z"
    mac: ENC[AES256_GCM,data:1P1zGlW3vT/iasXQBsr1eo2ci2oz6dUIaYLQrspjCtixtuHgKxdJjTYfTanPVxDynbg8ZOYJsBE0t1xecoq1RYu0Ym/L23ypuK6cbt03SSZtnX7eDTLz8f3I4M/Zuk0BkpxckwQLoK4YSb69masoTKigEldgZ3kODLrnVz/7LNo=,iv:FIP47L3OX3MUKrjskpdCRsIVd8QJ2bFAWMqcyuwrpB4=,tag:odXKYrgCZJwrPnHcZ+qcTw==,type:str]
    pgp:
        - created_at: "2026-05-24T06:33:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/J2BiN+msR8AQ//e3/yPnWFl2mph9AMl9Gn25g4A2hNbtB2u5e+PmjraQMX
            NduNNU4h99Baeeb4M/9WkvW9z84v7cJEhjDFF8kzoPwERAa4ozoXS/n6zvXmulMT
            cFtTo3MBJxy9APzDLkbnzPCULyEeZbvOAI08LNq+VTt/qGJrcODw2nSM5jWE4vqY
            fAmunBYV4hh5NQTcaZicNjKH6seNYzWM+tylkkmzg5g8sJXvKFIfTdfHI+H7FEDr
            k4fm7NhWwnVAMHeqNfALJIZnGScXxzq+roSOeFc/eCsEL75yZeHdpXXZtNH/o530
            7z1xIfvEtKzM8ukwei164n587Wj/hPV37GLmMYFOPcOD1xVKfX2GA0v2s0CwGpZT
            B24S/7bu5ibuObRFLiACvZmNJ+3UlG+4UUtItu+UiO45AKe2MQPz9NKTfoIJYXKT
            LDlieMDCiLAEU/M82U/kgP4obbxvZqM/BJTK2RlbYwLPvH8iRaZcuuo/j/G4Yjg3
            EAxNX8IMPas5D1Flowp6iRcrDcuK5Z2o1S9V4uNkaugaID5FUUF9livpBfPYAcpB
            d8HWy8klEiDBbVRsDO3F3EhI4osTiiqlzfRA3r9rFnVRRL6nJjm1/BwY+6KAQExm
            EY3x5kO0/xz6X7zoXDHXwCBcgpxWqft/ivnT69Wit/cf4WuAuJRBrYJH3gCaVcHS
            UQFMWbfyYTSgKmfUq+nK5hJvmuhRcKjmp98u4CAilF0SYmdz3kl/aDHsd5zJ96RB
            oSNU94vvkjgW6+/FOXGQtz8UnPB46YTPqM1+d/i/thKg8A==
            =685u
            -----END PGP MESSAGE-----
          fp: 04B1FD9EEE0A46AD62CCFF8C2EE05AF20EB391BA
    version: 3.13.0
