apiVersion: v1
data:
    token: ENC[AES256_GCM,data:WPkwgrIUtxaG2eRxbsprkrIFUD4/QdBcQU7ypVagPaK38pYVfoRrFbyPmGA0sRHAbz5rahvmlVhmq2P8iigaMS4JJhUWIwMeuryq4eKDJhP2A/JB2Lw9BkTg+9ZroeCxNKYXHRTj8I0HPHhnpxdDLEKvCr37uUI1l8EIZA==,iv:Clwz2OkHdJdGPFGpU5zbjI8CGMhl6M7DWbdJwHz1op4=,tag:1w63MOkDVqczr29OPVRV/w==,type:str]
kind: Secret
metadata:
    name: github-api-token
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T06:50:18Z"
    mac: ENC[AES256_GCM,data:HZxqjK8y8Zcaow10Ukpo/VVmx0IBHwMr68i7Zqr0Dc+49pG1kg1kWgbY+cgxpHnxIFfkR2IQ6xOIAl1bxRsDJp7VHeSVvqwimscLHdjwmbiJYN0pYO7xPQvfCIbvoJiNhv65YKVpMfH40LKxyFR87IwHqB1gFZLxvRe2AcZc3Rg=,iv:W0Hkhb1nENwlzopUJju4PIQKngOUi9B43u8Z/SlA5I4=,tag:ueEvQ3Aw8su3LhH+XDYwlg==,type:str]
    pgp:
        - created_at: "2026-05-24T06:50:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/J2BiN+msR8ARAAk8av3aR12WZhbh4yo6mAifpSa1WoGNNgPyeKFnoUjSRk
            8Gena6t4E/Q5EtXTvkBGr1lCP2pJe75FenwqZMn/+WYMTlnKSyiMo/DQcZXFe/aT
            i7SC6OakrMP3lIGSi7g8Z0dv3SLnMOzCuW3AJbv2mrUxY2xFVwqFmZXN1dpTsdOb
            hH8GdybxnZ1WFhpC7OieQ66rqRvsM3XYpa74KDKqIlum+rnCE6kuCdFP68KXaJGs
            wyJlEbcDHmGdKeWnGm6I33B4n07p7enwysxfrFYr8VsJW/hFmagA6TwQa/Cv1nl/
            TY1hSoZoUooLMq7jLJGtZxLHT23COp2KnVtJZ2HyghGrwBqeacFDEB4OdcagiJlp
            xWkqSI1Kvaphb68Hkq/gZLYFARwVjGOllObtPpTP+2rZImgcn+697hgMNLlHSvSO
            oEzrOPRTT9/JWLVQnncdmsgjLt9gVyik0uAx5VhLgtfRTRuE2+uwOx4/CUDQmliy
            Kg/bywiQHdWj2bF0E5WOeFRM4S21anIFr8PE7qIdflb9US3j6eytDV8ScZNE5Cm7
            ZyCq7nV+CPmnvBScgaTNjx5X+I5oC8brbjbQBwi7vligPdW//AuFATmH0EBL80XO
            KAKOJaQm04SPeWgKeLpKSymhB+0HGy9YvyWXPKj5LJ6pviKiY8vPmb9vH3GmQZLS
            XgEK8ATC1PlLbyXrfjoFYbpvZgPQnIegwdWv4Teb8oMlmWCAviigY6O8fh9cNN8t
            BOa87lyxd5gLB2BiHI2fkwJeSOa2PEMCKJcMoMcmi4MLcyyuObyUZKgNCAUZHuk=
            =B4ey
            -----END PGP MESSAGE-----
          fp: 04B1FD9EEE0A46AD62CCFF8C2EE05AF20EB391BA
    version: 3.13.0
