apiVersion: v1
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: flux-system-extra
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: slack-flux-notification-url
    namespace: flux-system
type: Opaque
data:
    address: ENC[AES256_GCM,data:UXMQiAAuocGk99HRKPhUFdh74VyfDu+ZN0eKrGyiTO8pAayNIYPXY27/eOjQZo3J3q3z7xuR6HvR8glpx+brQdVfRpXdfJ6I3IM2oUkRK+EESzzaaur3XXych/pqJRpzVvPGCGMByuzzvK78,iv:LTe1wzMltOGW6igcJwRXGvMNJnRIy7hf1OQHeR4OpnE=,tag:B8HYwwqSgoXDNZebpWFY0Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T06:42:59Z"
    mac: ENC[AES256_GCM,data:ebNDGpDlWyXyycUcovFCUIoHa6tlZABwmED8fgW5maMPUZ/5eEQBpjfc/Fv7ijOd27+yRjgZwUFiMR/B34tUkl85Zx1XfhviD1kvKaVJ/4WA7YO7mUOAUw2pLBWpqwFNyaHV5lVR52GFj2ZIX6RZCHFx1SzTwG5u7FMHpJ4/68Y=,iv:qGKJTQ2tmh1Gt7uJTKKn5ARzBwZ4btC2P51/0/4fO4k=,tag:zmzSZ53mir0VrgTv5gu3UQ==,type:str]
    pgp:
        - created_at: "2026-05-24T06:42:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/J2BiN+msR8AQ//dU9KaevF0W5uvxL6yn/0SPumRmbuy0Ttv2La5gyj9jMm
            Dn7V3yAV5nam4InWYiYVRrPEv+NAmP1knYvnI0twIQN/erfgcunALwE7bniRulDV
            rIU7Bll5qeZGlla10ZJS796/ZCu3pbMrEPqBtkT0GAZyNH/o7UuP/5iIOku8oAxk
            xqHkE/LE0LT31pzjlNppwcAekQL+u3/Cc2SL7TKn43D2eEEGBLm/VfPFcWVHHo8g
            iO0WtzFdGOUU8XqdJWsaONjV5LTn4iSo3VRFIDCrPVyy1WgMeiFknuyLqx5+AtX2
            ubBzzmpDsn0v1/w5scIzIgIw16gSKg0x45mtGHzpS8ir7D+2RnHK5AQFwCXlfbBq
            ZF6dU9quLN7j4Clxwhf7CjyYubRYkd80M+TnqR8cjKjjSQLthpegEeZHX9+njflQ
            aVeQ42g03OliUHlpH8I1z6yivr6tHnGiiXGHPRvkuqSOL5CQdcP8Ww6/dIv9fS4z
            fVDi5JpHOQjIcOd99zhxJ0roncFVHVO6CliKlX5VOHLC+WTOEfUYsY5V3PE5XpXn
            oP2ZYN0UyykB0b3Mp7xibha4rU9azQNlHgaEayNFbtL71IObYYTIiLQwq1fwfbxq
            TiM9pQJ0iLzDYBag836dzYkJ4fLSX0fjTkXlAzfDyQSHxOZH0rR49zS8xiDkCCjS
            XAGhtPk5udHhAoj7DP9DlfI4I5nZae5UMAV1ZkaGLW21xesbZZVhZdSyqX/YRmXH
            l4eTE7e/3pRBK24BCK6fGrPVMfKAw9HzNUQVswc3UwHhjTO2R77YiGGBhOM/
            =VOjw
            -----END PGP MESSAGE-----
          fp: 04B1FD9EEE0A46AD62CCFF8C2EE05AF20EB391BA
    version: 3.13.0
